# Generated by Django 5.0.6 on 2024-06-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_country_ggtrendsdailydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='short_name',
            field=models.CharField(default='UNKNOWN', max_length=10),
            preserve_default=False,
        ),
    ]
