# Generated by Django 5.0.6 on 2024-06-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_ggtrendsdailydata_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ggtrendsdailydata',
            old_name='name',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='ggtrendsdailydata',
            name='created_at',
        ),
    ]
