# Generated by Django 5.0.6 on 2024-06-06 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_name_ggtrendsdailydata_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='short_name',
            new_name='code',
        ),
    ]
