# Generated by Django 5.0.6 on 2024-06-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_short_name_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ggTrendsRealtimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
